server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions-slave.yaml

clients:
  - url: http://MONITORING_MASTER_PRIVATE_IP:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: node-1
          __path__: /var/log/*.log

  - job_name: container-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          host: node-1
          __path__: /var/lib/docker/containers/*/*-json.log
